/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DeliverySchedule;
import services.DeliveryScheduleService;

/**
 *
 * @author ASUS
 */
public class DriverScheduleGui extends javax.swing.JFrame {

    private DeliveryScheduleService scheduleService = new DeliveryScheduleService();

    /**
     * Creates new form DriverScheduleGui
     */
    public DriverScheduleGui() {
        initComponents();
        loadSchedules();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtScheduleId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtShipmentId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboDeliveryTime = new javax.swing.JTextField();
        btnAddSchedule = new javax.swing.JButton();
        btnUpdateSchedule = new javax.swing.JButton();
        btnDeleteSchedule = new javax.swing.JButton();
        btnClearSchedule = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSchedules = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Schedule ID");

        jLabel2.setText("Shipment ID");

        jLabel3.setText("Delivery Time(yyyy-mm-ddThh:mm)");

        btnAddSchedule.setBackground(new java.awt.Color(153, 255, 153));
        btnAddSchedule.setText("Add");
        btnAddSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddScheduleActionPerformed(evt);
            }
        });

        btnUpdateSchedule.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdateSchedule.setText("Update");
        btnUpdateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateScheduleActionPerformed(evt);
            }
        });

        btnDeleteSchedule.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteSchedule.setText("Remove");
        btnDeleteSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteScheduleActionPerformed(evt);
            }
        });

        btnClearSchedule.setText("Clear");
        btnClearSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearScheduleActionPerformed(evt);
            }
        });

        tableSchedules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Shipment Id", "ScheduleId", "Delivery Time"
            }
        ));
        jScrollPane1.setViewportView(tableSchedules);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtScheduleId)
                            .addComponent(txtShipmentId)
                            .addComponent(comboDeliveryTime, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAddSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScheduleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtShipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboDeliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSchedule)
                    .addComponent(btnUpdateSchedule)
                    .addComponent(btnDeleteSchedule)
                    .addComponent(btnClearSchedule)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateScheduleActionPerformed
        updateSchedule();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateScheduleActionPerformed

    private void btnDeleteScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteScheduleActionPerformed
        deleteSchedule();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteScheduleActionPerformed

    private void btnClearScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearScheduleActionPerformed
        clearForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearScheduleActionPerformed

    private void btnAddScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddScheduleActionPerformed
        addSchedule();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddScheduleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();;        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverScheduleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverScheduleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverScheduleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverScheduleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverScheduleGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSchedule;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearSchedule;
    private javax.swing.JButton btnDeleteSchedule;
    private javax.swing.JButton btnUpdateSchedule;
    private javax.swing.JTextField comboDeliveryTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSchedules;
    private javax.swing.JTextField txtScheduleId;
    private javax.swing.JTextField txtShipmentId;
    // End of variables declaration//GEN-END:variables
private void addSchedule() {
        try {
            int shipmentId = Integer.parseInt(txtShipmentId.getText());
            String deliveryTimeStr = comboDeliveryTime.getText().trim();

            // Parse the delivery time string to LocalDateTime
            LocalDateTime deliveryTime = LocalDateTime.parse(deliveryTimeStr);

            DeliverySchedule schedule = new DeliverySchedule();
            schedule.setShipmentId(shipmentId);
            schedule.setScheduledDeliveryTime(deliveryTime);

            boolean success = scheduleService.addSchedule(schedule);
            if (success) {
                loadSchedules();
                clearForm();
                JOptionPane.showMessageDialog(this, "Schedule added successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add schedule.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Shipment ID.");
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid delivery time format. Use yyyy-MM-ddTHH:mm.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void updateSchedule() {
        try {
            int scheduleId = Integer.parseInt(txtScheduleId.getText());
            int shipmentId = Integer.parseInt(txtShipmentId.getText());
            String deliveryTimeStr = comboDeliveryTime.getText().trim();

            LocalDateTime deliveryTime = LocalDateTime.parse(deliveryTimeStr);

            DeliverySchedule schedule = new DeliverySchedule();
            schedule.setScheduleId(scheduleId);
            schedule.setShipmentId(shipmentId);
            schedule.setScheduledDeliveryTime(deliveryTime);

            boolean success = scheduleService.updateSchedule(schedule);
            if (success) {
                loadSchedules();
                clearForm();
                JOptionPane.showMessageDialog(this, "Schedule updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update schedule.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Schedule ID or Shipment ID.");
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid delivery time format. Use yyyy-MM-ddTHH:mm.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void deleteSchedule() {
        try {
            int scheduleId = Integer.parseInt(txtScheduleId.getText());
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete this schedule?",
                    "Confirm Delete", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                boolean success = scheduleService.deleteSchedule(scheduleId);
                if (success) {
                    loadSchedules();
                    clearForm();
                    JOptionPane.showMessageDialog(this, "Schedule deleted successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete schedule.");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Schedule ID.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void clearForm() {
        txtScheduleId.setText("");
        txtShipmentId.setText("");
        comboDeliveryTime.setText("");
    }

    private void loadSchedules() {
        try {
            List<DeliverySchedule> schedules = scheduleService.getAllSchedules();

            // Table column names: "Shipment Id", "ScheduleId", "Delivery Time"
            DefaultTableModel model = (DefaultTableModel) tableSchedules.getModel();
            model.setRowCount(0); // Clear existing rows

            for (DeliverySchedule schedule : schedules) {
                Object[] row = new Object[3];
                row[0] = schedule.getShipmentId();
                row[1] = schedule.getScheduleId();
                // Format LocalDateTime to string for display
                row[2] = schedule.getScheduledDeliveryTime().toString();

                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading schedules: " + e.getMessage());
        }
    }
}
